<?php
/**
 * @file
 * Code for the Verbaili feature.
 */

include_once 'association_verbal.features.inc';

/**
 * Implements hook_permission().
 */
function association_verbal_permission() {
  return array(
    'create verbali content' => array(
      'title' => t('Create verbal content'),
      'description' => t('Enable users to create verbals.'),
    ),
    'update verbali content' => array(
      'title' => t('Update verbal content'),
      'description' => t('Enable users to update verbals.'),
    ),
    'delete verbali content' => array(
      'title' => t('Delete verbal content'),
      'description' => t('Enable users to delete verbals.'),
    ),
    'view verbali content' => array(
      'title' => t('View verbal content'),
      'description' => t('Enable users to view verbals.'),
    ),
  );
}


/**
 * Implements hook_node_access().
 */
function association_verbal_node_access($node, $op, $account) {
  $type = is_string($node) ? $node : $node->type;

  if ($type == 'verbali') {
    if (user_access($op . ' verbali content', $account)) {
      return NODE_ACCESS_ALLOW;
    }
    else {
      return NODE_ACCESS_DENY;
    }
  }

  // Returning nothing from this function would have the same effect.
  return NODE_ACCESS_IGNORE;
}
