<?php
/**
 * @file
 * drupalitalia d6 to d7 migration functions.
 */
define('DRUPALITALIA_FORUM_ARCHIVE_SECTION_TAXONOMY_ID', 56);
define('DRUPALITALIA_FORUM_NODE_ARCHIVE_LIMIT', 56);

function drupalitalia_d6_to_d7_migration_batch_1() {
  $operations = array();
  $results = db_query('SELECT nid FROM {node} WHERE changed < UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)');
  $nids = array();
  $i = 0;

  foreach ($results as $result) {
    if ($i < DRUPALITALIA_FORUM_NODE_ARCHIVE_LIMIT) {
      $nids[] = $result->nid;
      ++$i;
    } else {
      $operations[] = array('drupalitalia_forum_op_1', array($nids));
      $nids = array();
    }
  }

  return array(
    'operations' => $operations,
  );
}

function drupalitalia_d6_to_d7_migration_op_1(array $nids) {
  foreach ($nids as $nid) {
    $node = node_load($nid);

    $node->taxonomy_forums[LANGUAGE_NONE][0]['tid'] = DRUPALITALIA_FORUM_ARCHIVE_SECTION_TAXONOMY_ID;
    $node->forum_tid = DRUPALITALIA_FORUM_ARCHIVE_SECTION_TAXONOMY_ID;

    node_save($node);
  }
}